### ISSUE TITLE
TODO clearning

### ISSUE THREAD

**Issue by Ja-Sny** [Ja-Sny/project_Broccoli#14]
Please review the code and finish all TODOs.

**Comment by Ja-Sny** [comment]
- [ ] edit_post.html - 
- [ ] new_post.html - 
- [ ] register.html - 
- [ ] edit_user.html
